<?php

namespace SparrowSilence\FileUpload;

use Dcat\Admin\Form\Field;
use Illuminate\Contracts\View\Factory;
use Illuminate\View\View;

class FileUploadField extends Field
{
    protected $view = 'file-upload::index';

    public function __construct($column, $arguments = [])
    {
        parent::__construct($column, $arguments);
    }


    public function render(): Factory|string|View
    {
        $value = $this->value;
        $this->addVariables(compact('value'));
        return parent::render(); // TODO: Change the autogenerated stub
    }


}
